### ISSUE TITLE
MaterialAutoComplete z-index problem

### ISSUE THREAD

**Issue by ratuka** [GwtMaterialDesign/gwt-material-demo#14]
If i am add a MaterialAutoComplete to a MaterialModal's MaterialModalContent, the SuggestionDisplay displayed below the dialog.

**Comment by kevzlou7979** [comment]
Yeah we have this issue will update this as soon as possible :)

**Comment by kevzlou7979** [comment]
Duplicate : https://github.com/GwtMaterialDesign/gwt-material-addins/issues/32
