### ISSUE TITLE
AutoComplete (type=TEXT) example throw an exception 

### ISSUE THREAD

**Issue by ratuka** [GwtMaterialDesign/gwt-material-demo#16]
Open the console, type a letter, than select an option and you will see a "This widget's parent does not implement HasWidgets" exception

**Comment by kevzlou7979** [comment]
What version are you using? I've tried on the demo app and its working fine

**Comment by kevzlou7979** [comment]
<img src="http://i.imgur.com/0Ir6rlt.gif" />

**Comment by ratuka** [comment]
Latest snapshot demo with latest stable Firefox
<img width="960" alt="error" src="https://cloud.githubusercontent.com/assets/2168212/14518776/88c342cc-021a-11e6-8f98-524b4e194f88.png">

**Comment by ratuka** [comment]
<img width="960" alt="error2" src="https://cloud.githubusercontent.com/assets/2168212/14518815/cc9dcac6-021a-11e6-8f46-d982cb2ea375.png">

**Comment by ratuka** [comment]
<img width="960" alt="error3" src="https://cloud.githubusercontent.com/assets/2168212/14518842/0aa63290-021b-11e6-8d5b-2b929735160a.png">

**Comment by kevzlou7979** [comment]
https://github.com/GwtMaterialDesign/gwt-material-addins/issues/50 This is the same :) I will upload today the snapshot so that you can test the latest version on Maven.

**Comment by kevzlou7979** [comment]
Ok you can test now https://oss.sonatype.org/content/repositories/snapshots/com/github/gwtmaterialdesign/gwt-material-addins/1.5.0-SNAPSHOT/ It was updated the latest Maven repo for addins 4.14.16

**Comment by ratuka** [comment]
Unfortunately the new version still contain this bug

**Comment by kevzlou7979** [comment]
What browser are u using?

**Comment by ratuka** [comment]
Firefox 45.0.2, IE 11.0.9600.18205, Chrome 49.0.2623.112
