### ISSUE TITLE
Wrong link for starter template

### ISSUE THREAD

**Issue by steeveb972** [GwtMaterialDesign/gwt-material-demo#27]
Hello,

Current link for starter template demo is leading to http://gwtmaterialdesign.github.io/gwt-material-template/snapshot/ instead of http://gwtmaterialdesign.github.io/gwt-material-starter/snapshot/

**Comment by steeveb972** [comment]
I have proposed a pull request about this.

**Comment by kevzlou7979** [comment]
Ok thanks for catching this merged now your pr.
