### ISSUE TITLE
unable to run demo project

### ISSUE THREAD

**Issue by shankri** [GwtMaterialDesign/gwt-material-demo#3]
I have downloaded the latest code. When I run the demo I get an error asking me to include below 2 lines in GWT XML

set-configuration-property name="CssResource.enableGss" value="true"
set-configuration-property name="CssResource.legacy" value="true"

I resolve the error by adding above 2 lines but i see a BLANK page when I run the demo

<b>Additionally "MaterialDemo.ui.xml" has some merge issue and is messed up</b>

**Comment by kevzlou7979** [comment]
Hi the MaterialDemo.ui.xml is now cleaned

**Comment by BenDol** [comment]
This should be resolved now.
