### ISSUE TITLE
minimum row issue with material table v 1.0-rc3

### ISSUE THREAD

**Issue by yogitjain** [GwtMaterialDesign/gwt-material-demo#49]
Hello,
please help me at bellow points.
a) If number of rows in table is less then 5 the data table is throwing out of bound exception when it loads.
         Exception: java.lang.IndexOutOfBoundsException: fromIndex: 0, toIndex: 5, size: 2
b) When we load pager table for the very first time it is not showing row expand icon there.
![screenshot from 2016-12-03 16-45-54](https://cloud.githubusercontent.com/assets/23333467/20859028/44893b9a-b979-11e6-8f0f-01d183525913.png)

c) please refer image I have attached. I have popup in this page which is hidden by default but whenever I refresh the page popup is showing and after few seconds it gets invisible.
but till material version 1.0 rc2 it is running good.  
![screenshot from 2016-12-03 16-50-14](https://cloud.githubusercontent.com/assets/23333467/20859022/267320c6-b979-11e6-9291-e3f80fd965ba.png)

d) Also is it possible to get person object in in row expansion handler. 

thanks

**Comment by kevzlou7979** [comment]
With recent SNAPSHOTS and Rc6 this has beed fixed.
