### ISSUE TITLE
Validation not work

### ISSUE THREAD

**Issue by jhonsmall** [GwtMaterialDesign/gwt-material-demo#53]
When I enter a number console log show: **Caused by: java.lang.RuntimeException: Field must be a number.**

Same when click VALIDATE

https://gwtmaterialdesign.github.io/gwt-material-demo/#errors

![captura de pantalla de 2017-04-12 17-58-03](https://cloud.githubusercontent.com/assets/22354841/24983052/f1c04e58-1fe4-11e7-85a3-170b5f70fc5c.png)
![captura de pantalla de 2017-04-12 18-00-52](https://cloud.githubusercontent.com/assets/22354841/24983056/f9f9cba8-1fe4-11e7-8893-7ce145978e0a.png)

**Comment by kevzlou7979** [comment]
This was already solved in latest snapshot demo http://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#errors
