### ISSUE TITLE
"Download the JAR (Alternative)" downloads the 1.3.3 jar and not 1.4

### ISSUE THREAD

**Issue by mseele** [GwtMaterialDesign/gwt-material-demo#8]
Clicking on the "DOWNLOAD 1.4.0" under "Download the JAR (Alternative)
If you are not using maven you can download the latest Jar Release easily and add it in your classpath." downloads the 1.3.3 jar and not the 1.4.

**Comment by kevzlou7979** [comment]
This is solved on the snapshot , need to merge it on the main showcase gh page
