### ISSUE TITLE
Dialog example property dismissible is no corresponding with documentation

### ISSUE THREAD

**Issue by dardison** [GwtMaterialDesign/gwt-material-demo#95]
In the documentation example it said: **dismissable**

**Comment by kevzlou7979** [comment]
Oh nice catch, will update it soon

**Comment by kevzlou7979** [comment]
This was updated https://github.com/GwtMaterialDesign/gwt-material-demo/commit/f4888dd962d0dd7e0c591d4b7cbb3164ac3ecc9d - Let's wait for Travis CI Build to deploy the new demo.
